First crack at updated admin scripts

diff --git a/admin/pre-release b/admin/pre-release
--- a/admin/pre-release
+++ b/admin/pre-release
@@ -1,25 +1,26 @@
 #!/bin/bash
-#######################DO NOT USE YET########################
 
-## Build a framework release branch
+## Build framework release branch & distributables
 
 #---------------------------------------------------
 # Setup variables
 
-UPSTREAM=https://github.com/codeigniter4/CodeIgniter4.git
+. admin/config
+
+#---------------------------------------------------
+# Sanity check - are we underway already?
+if [ -n "$RELEASE" ]; then
+    echo -e "${BOLD}${ERROR}A release build is already underway${NORMAL}"
+    exit 1
+fi
+
 action=test
 version=4
 qualifier=
 
 branch=release-
 releasable='application docs public system writable README.md composer.json contributing.md env license.txt spark'
-release_empty='tests tests/_support'
 which=release
-
-BOLD='\033[1m'
-NORMAL='\033[0m'
-COLOR='\033[1;31m'
-ERROR='\033[0;31m'
 
 echo -e "${BOLD}${COLOR}CodeIgniter4 release builder${NORMAL}"
 echo '----------------------------'
@@ -29,7 +30,7 @@ echo '----------------------------'
 echo -e "${BOLD}Checking arguments...${NORMAL}"
 
 if [ $# -lt 1 ]; then
-    echo -e "${BOLD}Usage: admin/release version# pre-release-qualifier${NORMAL}"
+    echo -e "${BOLD}Usage: admin/pre-release version# pre-release-qualifier${NORMAL}"
     exit 1
 fi
 
@@ -39,7 +40,8 @@ if [ $# -gt 1 ]; then
     qualifier="-${2}"
     which='pre-release'
 fi
-branch="release-$version$qualifier"
+RELEASE=$version$qualifier
+branch="release-$RELEASE"
 
 #---------------------------------------------------
 # Create the release branch
@@ -57,7 +59,7 @@ echo -e "${BOLD}Updating version dependencies${NORMAL}"
 function check_unique {
     count=`grep -c '$1' < $2 | wc -l`
     if [ $count -ne 1 ]; then
-        echo -e "${BOLD}${COLOR}$2 has ${count} occurences of '$1'${NORMAL}"
+        echo -e "${BOLD}${COLOR}$2 has ${count} occurrences of '$1'${NORMAL}"
         exit 1
     fi
 }
@@ -65,31 +67,43 @@ function check_unique {
 # Make sure there is only one line to affect in each file
 check_unique "const CI_VERSION" 'system/CodeIgniter.php'
 check_unique "release =" 'user_guide_src/source/conf.py'
-check_unique "|release|" 'user_guide_src/source/changelog.rst'
-check_unique "Release Date.*Not Released" 'user_guide_src/source/changelog.rst'
+check_unique "|release|" 'user_guide_src/source/changelogs/index.rst'
+check_unique "Release Date.*Not Released" 'user_guide_src/source/changelogs/index.rst'
 
 # CI_VERSION definition in system/CodeIgniter.php
-sed -i "/const CI_VERSION/s/'.*'/'${version}${qualifier}'/" system/CodeIgniter.php
+sed -i "/const CI_VERSION/s/'.*'/'${RELEASE}'/" system/CodeIgniter.php
 
 # release substitution variable in user_guide_src/source/conf.py
-sed -i "/release =/s/'.*'/'${version}${qualifier}'/" user_guide_src/source/conf.py
+sed -i "/release =/s/'.*'/'${RELEASE}'/" user_guide_src/source/conf.py
 
 # version & date in user_guide_src/source/changelog.rst
-sed -i "/|release|/s/|.*|/${version}${qualifier}/" user_guide_src/source/changelog.rst
-sed -i "/Release Date/s/Not Released/$(date +'%B %d, %Y')/" user_guide_src/source/changelog.rst
+sed -i "/|release|/s/|.*|/${RELEASE}/" user_guide_src/source/changelogs/index.rst
+sed -i "/Release Date/s/Not Released/$(date +'%B %d, %Y')/" user_guide_src/source/changelogs/index.rst
+
+# establish version-specific changelog
+mv user_guide_src/source/changelogs/next.rst user_guide_src/source/changelogs/${RELEASE}.rst
+# start new changelog for next version
 
 #---------------------------------------------------
 # Setup the distribution folders
+echo -e "${BOLD}Building repo distributions${NORMAL}"
+
+function setup_repo {
+    mkdir dist/$1
+    cd dist/$1
+    git init
+    git remote add origin ${CI_ORG}/$1
+    git fetch
+}
 
 if [ -d dist ]; then
     rm -rf dist/
 fi
 mkdir dist
 
-if [ -d build ]; then
-    rm -rf build/
-fi
-mkdir build
+setup_repo framework
+setup_repo docs
+setup_repo app-starter
 
 #---------------------------------------------------
 # Generate the user guide
@@ -104,32 +118,34 @@ make epub
 
 cd ..
 
-mv user_guide_src/build/html build/docs
+cp -rf user_guide_src/build/html dist/docs
+mv user_guide_src/built/html dist/framework/docs
+
+cd dist/docs
+git checkout gh-pages
+cp -r ../../docs .
 
 #---------------------------------------------------
 # And finally, get ready for merging
 git add .
-git commit -m "Release ${version}${qualifier}"
+git commit -m "Release ${RELEASE}"
 
 #---------------------------------------------------
 # Hide stuff from the release bundle
 echo -e "${BOLD}Build the distributables${NORMAL}"
 
-for f in $releasable; do
-    cp -r $f build/
-done
-for f in $release_empty; do
-    mkdir build/$f
-done
-
 # add the docs
-mv user_guide_src/build/epub/CodeIgniter4.epub dist/CodeIgniter-${version}${qualifier}.epub
+mv user_guide_src/build/epub/CodeIgniter4.epub dist/CodeIgniter-${BRANCH}.epub
 
 cd build
-zip -r  ../dist/v${version}${qualifier}.zip *
-tar -zcf  ../dist/v${version}${qualifier}.tar.gz *
+zip -r  ../dist/v${RELEASE}.zip *
+tar -zcf  ../dist/v${RELEASE}.tar.gz *
+
+#---------------------------------------------------
+# Save the in-progress branch designation for following steps
+sed -i "/RELEASE=/s/=.*/=${RELEASE}/" admin/config
 
 #---------------------------------------------------
 # Done for now
 echo -e "${BOLD}Your $branch branch is ready to inspect.${NORMAL}"
-echo -e "${BOLD}Follow the directions in release.md to continue.${NORMAL}"
+echo -e "${BOLD}Follow the directions in workflow.md to continue.${NORMAL}"
diff --git a/admin/release b/admin/release
--- a/admin/release
+++ b/admin/release
@@ -1,12 +1,21 @@
 #!/bin/bash
-#######################DO NOT USE YET########################
 
 ## Build the distributable repo branches
+
+. admin/config
+
+#---------------------------------------------------
+# Sanity check - are we underway already?
+if [ "$BRANCH" ]; then
+    echo -e "${BOLD}${ERROR}No release build is underway${NORMAL}"
+    exit 1
+fi
+
 
 #---------------------------------------------------
 # Setup variables
 
-UPSTREAM=https://github.comcodeigniter4/CodeIgniter4.git
+UPSTREAM=${CI_ORG}CodeIgniter4.git
 action=test
 version=4
 qualifier=
