Trying to fix the nightly docs action again.

diff --git a/.github/workflows/docs_nightly.yml b/.github/workflows/docs_nightly.yml
--- a/.github/workflows/docs_nightly.yml
+++ b/.github/workflows/docs_nightly.yml
@@ -16,29 +16,29 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+    - uses: actions/checkout@v2
 
-      - name: Build docs
-        uses: ammaraskar/sphinx-action@master
-        with:
-          docs-folder: "user_guide_src/"
+    # Build the current docs
+    - uses: ammaraskar/sphinx-action@master
+      with:
+        docs-folder: "user_guide_src/"
 
-      - name: Commit documentation changes
-        run: |
-          git clone https://github.com/codeigniter4/CodeIgniter4.git --branch gh-pages --single-branch gh-pages
-          cp -r user_guide_src/_build/html/* gh-pages/
-          cd gh-pages
-          git config --local user.email "action@github.com"
-          git config --local user.name "${GITHUB_ACTOR}"
-          git add .
-          git commit -m "Update documentation" -a || true
-          # The above command will fail if no changes were present, so we ignore
-          # that.
+    # Commit changes to the gh-pages branch
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/codeigniter4/CodeIgniter4.git --branch gh-pages --single-branch gh-pages
+        cp -r user_guide_src/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "${GITHUB_ACTOR}"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
 
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          branch: gh-pages
-          directory: gh-pages
-          github_token: ${{ secrets.ACCESS_TOKEN }}
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.ACCESS_TOKEN }}
